baseURL: https://sparkwing.com.au
languageCode: en-us
title: SparkWing

# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:  
  # Used as meta data; describe your site to make BAWTs happy
  description: Find your dream team.
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/SparkWingLogo_2022_03_02-1.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  fullimage:
    image: Find your dream team.gif
  hero:
    # Main hero title
    title: Find your dream team
    # Hero subtitle (optional)
    subtitle: SparkWing is taking off on a journey to change the way we build teams for the better. 
    # Button text
    buttontext: Learn More
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: Find your dream team.gif
    # Footer logos (from static/images/logos/clients/___.svg)
    #clientlogos:
    #- notreadyyet
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Job List
    url: /jobs
  - title: Post a Job
    url: /new
  - title: Contribute
    url: https://opencollective.com/sparkwing
  featurecards:
    title: How it works
    tiles:
    - title: Plan the Job
      icon: image-one
      text: We'll help you describe how a new teammate can help
      url: /
      buttonText: Get a Job Plan
    - title: Working Interviews
      icon: image-two
      text: Work together before making a decision
      url: /
      buttonText: Find Open Jobs
    - title: Anonymous Job Applications
      icon: image-three
      text: Share your work, not your personal details
      url: /
      buttonText: Sign Up
  textlist:
    title: Purpose and Vision
    subtitle: 
    features:
    - title: Purpose
      text: Provide a service that seamlessly connects the right people to the right teams
      icon: doc-sync
      # Icon (from /images/illustrations/icons/___.svg)
    - title: Vision
      text: Help people find their best work with the right team.
      icon: doc-sync
  testimonials:
    title: How have we helped?
    subtitle: This is what people are saying.
    clients:
    - name: 
      quote: I have never seen anything like this!
      job: Technology Leader
      img: 
    - name: 
      quote: This is the best thing. I feel confident now.
      job: Small Business Owner
      img: 
    - name: 
      quote: Thank you for connecting me with this role. I am enjoying it.
      job: Senior Developer
      img: 
  contact: true
  footer:
    # Logo (from /images/logos/___)
    logo: SparkWingLogo_2022_03_02-1.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    externalLinksTitle: Contribute
    externalLinks:
      - name: To our collective
        link: https://opencollective.com/sparkwing
        icon: opencollective-foundation.png
 #   - name: To our source
 #     link: https://github.com/sparkwing # coming soon
      #icon: github
    quicklinks:
      column1:
        title: "About Us"
        links:
        - text: info@sparkwing.me
          link: "mailto: info@sparkwing.me"
        - text: "ABN: 69 657 372 677"
          link: /
      # column2:
      #   title: "Blog"
      #   links:
      #   - text: Latest news
      #     link: /blog/first
      #   - text: All articles
      #     link: /
  sovereignty:  SparkWing works from Wadawarrung land and acknowledges that sovereignty of this land has not been ceded.
