baseURL: https://sparkwing.com.au
languageCode: en-us
title: SparkWing
theme: hugo-fresh

# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:  
  # Used as meta data; describe your site to make Google Bots happy
  description: Find your dream team.
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/SparkWing.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Find your dream team
    # Hero subtitle (optional)
    subtitle: SparkWing is taking off on a journey to transform the way Australia builds teams.
    # Button text
    buttontext: Learn More
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: logos/Hero.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    #clientlogos:
    #- notreadyyet
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Features
    url: /
  - title: Pricing
    url: /
  - title: Dropdown
    sublinks:
    - title: Dropdown item
      url: /
    - title: Dropdown item
      url: /
    - title: Dropdown item
      url: /
    button: true
  featurecards:
    title: How SparkWing can help
    subtitle: find your dream team
    tiles:
    - title: Job Plans
      icon: mouse-globe
      text: Concierge MVP job plan writing service
      url: /
      buttonText: Get a Job Plan
    - title: Working Interviews
      icon: laptop-cloud
      text: Work together before making a decision.
      url: /
      buttonText: Find Open Jobs
    - title: Anonymous Job Applications
      icon: plug-cloud
      text: Share your work, not your personal details.
      url: /
      buttonText: Sign Up
  textlist:
    title: Our Purpose and Vision
    subtitle: 
    features:
    - title: Purpose
      text: Provide a service that seamlessly connects the right people to the right teams for a fair price.
      icon: doc-sync
      # Icon (from /images/illustrations/icons/___.svg)
    - title: Vision
      text: is to help people find their best work with the right team.
      icon: doc-sync
  # bigimage:
  #   title: One platform
  #   subtitle: To rule them all
  #   image: illustrations/mockups/app-mockup.png
  #   buttonText: Get started
  #   buttonLink: "#"
  # testimonials:
  #   title: Our Clients love us!
  #   subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #   clients:
  #   - name: Irma Walters
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Accountant
  #     img: 1
  #   - name: John Bradley
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Financial Analyst
  #     img: 2
  #   - name: Gary Blackman
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: HR Manager
  #     img: 3
  contact: true
  footer:
    # Logo (from /images/logos/___)
    logo: SW-Sticker.png
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://linkedin.com/sparkwing
      icon: linkedin
    # - link: https://github.com/sparkwing # will we need this to be public for any reason? 
      # Icons are from Font Awesome
      #icon: github
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
